<a href="https://colab.research.google.com/github/emilianot845/Templos_THC_Tareas/blob/main/19_oct_23_Templos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as lol
lista= lol.array([16,12,1,2,4])
print(lista)
print(type(lista))

[16 12  1  2  4]
<class 'numpy.ndarray'>


In [3]:
Numero= lol.array(17)
print(Numero)

17


In [4]:
#Las dimensiones se pueden ver por el numero de corchetes que hay
Num= lol.array([[4,5,6],[8,9,7]])
print(Num)

[[4 5 6]
 [8 9 7]]


In [6]:
Trid=lol.array([[[4,5,6],[8,2,3],[3,2,2]]])
print(Trid)

[[[4 5 6]
  [8 2 3]
  [3 2 2]]]


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2do elemento de la 1er Fila: ', arr[0, 1])

In [10]:
# Con numpy
import numpy as lol
matriz = lol.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
suma = lol.sum(matriz)
print(suma)

45


In [11]:
# con listas :
matriz = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]
suma = 0
for fila in matriz:
    suma += sum(fila)
print(suma)

45


In [13]:
# Definir dos matrices 3x3
matrix1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
matrix2 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
# Inicializar una matriz resultado 1x3 con ceros
result = [0, 0, 0]
# Realizar el producto escalar por columnas
for i in range(3):
    for j in range(3):
        result[i] += matrix1[j][i] * matrix2[j][i]
# Imprimir el resultado
print(result)

[66, 93, 126]


In [14]:
import numpy as np
# Define la función ProdPunto
def ProdPunto(arr1, arr2):
    return np.dot(arr1, arr2)
arr2 = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
arr3 = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
Pp_por_reng = np.array([0, 0, 0])
Pp_por_col = np.array([0, 0, 0])
for i in range(len(arr2)):
    Pp_por_reng[i] = ProdPunto(arr2[i], arr3[i])
Pp_por_reng

array([3, 3, 3])