<a href="https://colab.research.google.com/github/emilianot845/Templos_THC_Tareas/blob/main/24_10_23_Templos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as sp
lol= sp.array([2,4,6,8,10])
print(lol[0:])

[ 2  4  6  8 10]


In [17]:
import numpy as sp
lol= sp.array([2,4,6,8,10])
print(lol[1])

4


In [18]:
import numpy as sp
lol= sp.array([1,3,2,5,7,10,14,6,2])
print(lol[0:6:2])

[1 2 7]


In [19]:
import numpy as sp
lol= sp.array([1,3,2,5,7,10,14,6,2])
print(lol[::1])
"""Aqui el salto va de uno en uno, por lo que en realidad da todos los elementos de la lista en orden"""

[ 1  3  2  5  7 10 14  6  2]


In [22]:
#Ahora lo haremos con matrices
import numpy as sp
jaja= sp.array([[1,3,2,5,7,10],[1,2,3,4,5,6]])
print(jaja[0, 0:5:2])

[1 2 7]


In [23]:

import numpy as sp
jaja= sp.array([[1,3,2,5,7,10],[1,2,3,4,5,6]])
print(jaja[0, :])

[ 1  3  2  5  7 10]


In [24]:

import numpy as sp
jaja= sp.array([[1,3,2,5,7,10],[1,2,3,4,5,6]])
print(jaja[0:2, 2])

[2 3]


In [28]:
#Recordar que python empieza desde el 0, si el indice marca 0:5, en realidad va desde el 0 al 1,2,3,4
import numpy as sp
jaja= sp.array([[1,3,2,5,7,10],[1,2,3,4,5,6]])
print(jaja[0:2, 1:4])

[[3 2 5]
 [2 3 4]]


In [31]:
#Arreglos ahora para indices, no para sacar elementos
import numpy as ind
XD=ind.array([1,2,6,2,7,10,2,9,15,2])
Holi= ind.where(XD == 2)
print(Holi)

(array([1, 3, 6, 9]),)


In [35]:
import numpy as xp
x=xp.array([1,2,3])
y=xp.array([4,5,6])
suma=x+y
print(f"La suma de las matrices es {suma}")

La suma de ambas listas es [5 7 9]


In [36]:
import numpy as xp
x=xp.array([4,3,7])
y=xp.array([8,4,3])
resta=x+(-y)
print(f"La resta de las matrices es {resta}")

La resta de ambas listas es [-4 -1  4]


In [37]:
import numpy as xp
x=xp.array([10,6,1])
y=xp.array([4,5,6])
mult=x*y
print(f"La multiplicacion de las matrices es {mult}")

La multiplicacion de las matrices es [40 30  6]


In [40]:
import numpy as xp
x=xp.linspace(0,1,4)
x

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [41]:
xp.random.randint(0,10,size=1)

array([8])

In [ ]:
#Pedir al usuario un numero del 1 al 10 y adivinarlo
